/* soapServer.c
   Generated by gSOAP 2.7.13 from kbws.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.7.13 2010-11-03 18:00:03 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runBlast"))
		return soap_serve_ns1__runBlast(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runCentroidfold"))
		return soap_serve_ns1__runCentroidfold(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runClustalw"))
		return soap_serve_ns1__runClustalw(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runFetchData"))
		return soap_serve_ns1__runFetchData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runFetchBatch"))
		return soap_serve_ns1__runFetchBatch(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runGenemarkhmm"))
		return soap_serve_ns1__runGenemarkhmm(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runGlimmer"))
		return soap_serve_ns1__runGlimmer(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runKalign"))
		return soap_serve_ns1__runKalign(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runMafft"))
		return soap_serve_ns1__runMafft(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runMuscle"))
		return soap_serve_ns1__runMuscle(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runPhobius"))
		return soap_serve_ns1__runPhobius(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runProtpars"))
		return soap_serve_ns1__runProtpars(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runProtdist"))
		return soap_serve_ns1__runProtdist(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnapars"))
		return soap_serve_ns1__runDnapars(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnapenny"))
		return soap_serve_ns1__runDnapenny(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnacomp"))
		return soap_serve_ns1__runDnacomp(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnainvar"))
		return soap_serve_ns1__runDnainvar(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnaml"))
		return soap_serve_ns1__runDnaml(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnamlk"))
		return soap_serve_ns1__runDnamlk(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDnadist"))
		return soap_serve_ns1__runDnadist(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runGendist"))
		return soap_serve_ns1__runGendist(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runSeqboot"))
		return soap_serve_ns1__runSeqboot(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runRestml"))
		return soap_serve_ns1__runRestml(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runClique"))
		return soap_serve_ns1__runClique(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runFitch"))
		return soap_serve_ns1__runFitch(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runKitsch"))
		return soap_serve_ns1__runKitsch(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runNeighbor"))
		return soap_serve_ns1__runNeighbor(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runContml"))
		return soap_serve_ns1__runContml(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runMix"))
		return soap_serve_ns1__runMix(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runPenny"))
		return soap_serve_ns1__runPenny(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDollop"))
		return soap_serve_ns1__runDollop(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runDolpenny"))
		return soap_serve_ns1__runDolpenny(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runPsort"))
		return soap_serve_ns1__runPsort(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runPsort2"))
		return soap_serve_ns1__runPsort2(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runPsortb"))
		return soap_serve_ns1__runPsortb(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runSsearch"))
		return soap_serve_ns1__runSsearch(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runTcoffee"))
		return soap_serve_ns1__runTcoffee(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runtRNAscan"))
		return soap_serve_ns1__runtRNAscan(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runWeblogo"))
		return soap_serve_ns1__runWeblogo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runWolfPsort"))
		return soap_serve_ns1__runWolfPsort(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:runRNAfold"))
		return soap_serve_ns1__runRNAfold(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:showBlastDB"))
		return soap_serve_ns1__showBlastDB(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:map2PathwayProjector"))
		return soap_serve_ns1__map2PathwayProjector(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:checkStatus"))
		return soap_serve_ns1__checkStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:checkStatus_retJobid"))
		return soap_serve_ns1__checkStatus_USCOREretJobid(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getResult"))
		return soap_serve_ns1__getResult(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getMultiResult"))
		return soap_serve_ns1__getMultiResult(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runBlast(struct soap *soap)
{	struct ns1__runBlast soap_tmp_ns1__runBlast;
	struct ns1__runBlastResponse soap_tmp_ns1__runBlastResponse;
	char * soap_tmp_string;
	soap_default_ns1__runBlastResponse(soap, &soap_tmp_ns1__runBlastResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runBlastResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runBlast(soap, &soap_tmp_ns1__runBlast);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runBlast(soap, &soap_tmp_ns1__runBlast, "ns1:runBlast", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runBlast(soap, soap_tmp_ns1__runBlast._in0, soap_tmp_ns1__runBlast._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runBlastResponse(soap, &soap_tmp_ns1__runBlastResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runBlastResponse(soap, &soap_tmp_ns1__runBlastResponse, "ns1:runBlastResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runBlastResponse(soap, &soap_tmp_ns1__runBlastResponse, "ns1:runBlastResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runCentroidfold(struct soap *soap)
{	struct ns1__runCentroidfold soap_tmp_ns1__runCentroidfold;
	struct ns1__runCentroidfoldResponse soap_tmp_ns1__runCentroidfoldResponse;
	char * soap_tmp_string;
	soap_default_ns1__runCentroidfoldResponse(soap, &soap_tmp_ns1__runCentroidfoldResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runCentroidfoldResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runCentroidfold(soap, &soap_tmp_ns1__runCentroidfold);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runCentroidfold(soap, &soap_tmp_ns1__runCentroidfold, "ns1:runCentroidfold", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runCentroidfold(soap, soap_tmp_ns1__runCentroidfold._in0, soap_tmp_ns1__runCentroidfold._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runCentroidfoldResponse(soap, &soap_tmp_ns1__runCentroidfoldResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runCentroidfoldResponse(soap, &soap_tmp_ns1__runCentroidfoldResponse, "ns1:runCentroidfoldResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runCentroidfoldResponse(soap, &soap_tmp_ns1__runCentroidfoldResponse, "ns1:runCentroidfoldResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runClustalw(struct soap *soap)
{	struct ns1__runClustalw soap_tmp_ns1__runClustalw;
	struct ns1__runClustalwResponse soap_tmp_ns1__runClustalwResponse;
	char * soap_tmp_string;
	soap_default_ns1__runClustalwResponse(soap, &soap_tmp_ns1__runClustalwResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runClustalwResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runClustalw(soap, &soap_tmp_ns1__runClustalw);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runClustalw(soap, &soap_tmp_ns1__runClustalw, "ns1:runClustalw", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runClustalw(soap, soap_tmp_ns1__runClustalw._in0, soap_tmp_ns1__runClustalw._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runClustalwResponse(soap, &soap_tmp_ns1__runClustalwResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runClustalwResponse(soap, &soap_tmp_ns1__runClustalwResponse, "ns1:runClustalwResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runClustalwResponse(soap, &soap_tmp_ns1__runClustalwResponse, "ns1:runClustalwResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runFetchData(struct soap *soap)
{	struct ns1__runFetchData soap_tmp_ns1__runFetchData;
	struct ns1__runFetchDataResponse soap_tmp_ns1__runFetchDataResponse;
	char * soap_tmp_string;
	soap_default_ns1__runFetchDataResponse(soap, &soap_tmp_ns1__runFetchDataResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runFetchDataResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runFetchData(soap, &soap_tmp_ns1__runFetchData);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runFetchData(soap, &soap_tmp_ns1__runFetchData, "ns1:runFetchData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runFetchData(soap, soap_tmp_ns1__runFetchData._in0, soap_tmp_ns1__runFetchData._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runFetchDataResponse(soap, &soap_tmp_ns1__runFetchDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runFetchDataResponse(soap, &soap_tmp_ns1__runFetchDataResponse, "ns1:runFetchDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runFetchDataResponse(soap, &soap_tmp_ns1__runFetchDataResponse, "ns1:runFetchDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runFetchBatch(struct soap *soap)
{	struct ns1__runFetchBatch soap_tmp_ns1__runFetchBatch;
	struct ns1__runFetchBatchResponse soap_tmp_ns1__runFetchBatchResponse;
	char * soap_tmp_string;
	soap_default_ns1__runFetchBatchResponse(soap, &soap_tmp_ns1__runFetchBatchResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runFetchBatchResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runFetchBatch(soap, &soap_tmp_ns1__runFetchBatch);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runFetchBatch(soap, &soap_tmp_ns1__runFetchBatch, "ns1:runFetchBatch", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runFetchBatch(soap, soap_tmp_ns1__runFetchBatch._in0, soap_tmp_ns1__runFetchBatch._in1, soap_tmp_ns1__runFetchBatch._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runFetchBatchResponse(soap, &soap_tmp_ns1__runFetchBatchResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runFetchBatchResponse(soap, &soap_tmp_ns1__runFetchBatchResponse, "ns1:runFetchBatchResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runFetchBatchResponse(soap, &soap_tmp_ns1__runFetchBatchResponse, "ns1:runFetchBatchResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runGenemarkhmm(struct soap *soap)
{	struct ns1__runGenemarkhmm soap_tmp_ns1__runGenemarkhmm;
	struct ns1__runGenemarkhmmResponse soap_tmp_ns1__runGenemarkhmmResponse;
	char * soap_tmp_string;
	soap_default_ns1__runGenemarkhmmResponse(soap, &soap_tmp_ns1__runGenemarkhmmResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runGenemarkhmmResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runGenemarkhmm(soap, &soap_tmp_ns1__runGenemarkhmm);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runGenemarkhmm(soap, &soap_tmp_ns1__runGenemarkhmm, "ns1:runGenemarkhmm", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runGenemarkhmm(soap, soap_tmp_ns1__runGenemarkhmm._in0, soap_tmp_ns1__runGenemarkhmm._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runGenemarkhmmResponse(soap, &soap_tmp_ns1__runGenemarkhmmResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runGenemarkhmmResponse(soap, &soap_tmp_ns1__runGenemarkhmmResponse, "ns1:runGenemarkhmmResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runGenemarkhmmResponse(soap, &soap_tmp_ns1__runGenemarkhmmResponse, "ns1:runGenemarkhmmResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runGlimmer(struct soap *soap)
{	struct ns1__runGlimmer soap_tmp_ns1__runGlimmer;
	struct ns1__runGlimmerResponse soap_tmp_ns1__runGlimmerResponse;
	char * soap_tmp_string;
	soap_default_ns1__runGlimmerResponse(soap, &soap_tmp_ns1__runGlimmerResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runGlimmerResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runGlimmer(soap, &soap_tmp_ns1__runGlimmer);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runGlimmer(soap, &soap_tmp_ns1__runGlimmer, "ns1:runGlimmer", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runGlimmer(soap, soap_tmp_ns1__runGlimmer._in0, soap_tmp_ns1__runGlimmer._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runGlimmerResponse(soap, &soap_tmp_ns1__runGlimmerResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runGlimmerResponse(soap, &soap_tmp_ns1__runGlimmerResponse, "ns1:runGlimmerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runGlimmerResponse(soap, &soap_tmp_ns1__runGlimmerResponse, "ns1:runGlimmerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runKalign(struct soap *soap)
{	struct ns1__runKalign soap_tmp_ns1__runKalign;
	struct ns1__runKalignResponse soap_tmp_ns1__runKalignResponse;
	char * soap_tmp_string;
	soap_default_ns1__runKalignResponse(soap, &soap_tmp_ns1__runKalignResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runKalignResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runKalign(soap, &soap_tmp_ns1__runKalign);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runKalign(soap, &soap_tmp_ns1__runKalign, "ns1:runKalign", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runKalign(soap, soap_tmp_ns1__runKalign._in0, soap_tmp_ns1__runKalign._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runKalignResponse(soap, &soap_tmp_ns1__runKalignResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runKalignResponse(soap, &soap_tmp_ns1__runKalignResponse, "ns1:runKalignResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runKalignResponse(soap, &soap_tmp_ns1__runKalignResponse, "ns1:runKalignResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runMafft(struct soap *soap)
{	struct ns1__runMafft soap_tmp_ns1__runMafft;
	struct ns1__runMafftResponse soap_tmp_ns1__runMafftResponse;
	char * soap_tmp_string;
	soap_default_ns1__runMafftResponse(soap, &soap_tmp_ns1__runMafftResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runMafftResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runMafft(soap, &soap_tmp_ns1__runMafft);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runMafft(soap, &soap_tmp_ns1__runMafft, "ns1:runMafft", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runMafft(soap, soap_tmp_ns1__runMafft._in0, soap_tmp_ns1__runMafft._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runMafftResponse(soap, &soap_tmp_ns1__runMafftResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runMafftResponse(soap, &soap_tmp_ns1__runMafftResponse, "ns1:runMafftResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runMafftResponse(soap, &soap_tmp_ns1__runMafftResponse, "ns1:runMafftResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runMuscle(struct soap *soap)
{	struct ns1__runMuscle soap_tmp_ns1__runMuscle;
	struct ns1__runMuscleResponse soap_tmp_ns1__runMuscleResponse;
	char * soap_tmp_string;
	soap_default_ns1__runMuscleResponse(soap, &soap_tmp_ns1__runMuscleResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runMuscleResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runMuscle(soap, &soap_tmp_ns1__runMuscle);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runMuscle(soap, &soap_tmp_ns1__runMuscle, "ns1:runMuscle", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runMuscle(soap, soap_tmp_ns1__runMuscle._in0, soap_tmp_ns1__runMuscle._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runMuscleResponse(soap, &soap_tmp_ns1__runMuscleResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runMuscleResponse(soap, &soap_tmp_ns1__runMuscleResponse, "ns1:runMuscleResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runMuscleResponse(soap, &soap_tmp_ns1__runMuscleResponse, "ns1:runMuscleResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runPhobius(struct soap *soap)
{	struct ns1__runPhobius soap_tmp_ns1__runPhobius;
	struct ns1__runPhobiusResponse soap_tmp_ns1__runPhobiusResponse;
	char * soap_tmp_string;
	soap_default_ns1__runPhobiusResponse(soap, &soap_tmp_ns1__runPhobiusResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runPhobiusResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runPhobius(soap, &soap_tmp_ns1__runPhobius);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runPhobius(soap, &soap_tmp_ns1__runPhobius, "ns1:runPhobius", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runPhobius(soap, soap_tmp_ns1__runPhobius._in0, soap_tmp_ns1__runPhobius._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runPhobiusResponse(soap, &soap_tmp_ns1__runPhobiusResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runPhobiusResponse(soap, &soap_tmp_ns1__runPhobiusResponse, "ns1:runPhobiusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runPhobiusResponse(soap, &soap_tmp_ns1__runPhobiusResponse, "ns1:runPhobiusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runProtpars(struct soap *soap)
{	struct ns1__runProtpars soap_tmp_ns1__runProtpars;
	struct ns1__runProtparsResponse soap_tmp_ns1__runProtparsResponse;
	char * soap_tmp_string;
	soap_default_ns1__runProtparsResponse(soap, &soap_tmp_ns1__runProtparsResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runProtparsResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runProtpars(soap, &soap_tmp_ns1__runProtpars);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runProtpars(soap, &soap_tmp_ns1__runProtpars, "ns1:runProtpars", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runProtpars(soap, soap_tmp_ns1__runProtpars._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runProtparsResponse(soap, &soap_tmp_ns1__runProtparsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runProtparsResponse(soap, &soap_tmp_ns1__runProtparsResponse, "ns1:runProtparsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runProtparsResponse(soap, &soap_tmp_ns1__runProtparsResponse, "ns1:runProtparsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runProtdist(struct soap *soap)
{	struct ns1__runProtdist soap_tmp_ns1__runProtdist;
	struct ns1__runProtdistResponse soap_tmp_ns1__runProtdistResponse;
	char * soap_tmp_string;
	soap_default_ns1__runProtdistResponse(soap, &soap_tmp_ns1__runProtdistResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runProtdistResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runProtdist(soap, &soap_tmp_ns1__runProtdist);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runProtdist(soap, &soap_tmp_ns1__runProtdist, "ns1:runProtdist", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runProtdist(soap, soap_tmp_ns1__runProtdist._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runProtdistResponse(soap, &soap_tmp_ns1__runProtdistResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runProtdistResponse(soap, &soap_tmp_ns1__runProtdistResponse, "ns1:runProtdistResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runProtdistResponse(soap, &soap_tmp_ns1__runProtdistResponse, "ns1:runProtdistResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnapars(struct soap *soap)
{	struct ns1__runDnapars soap_tmp_ns1__runDnapars;
	struct ns1__runDnaparsResponse soap_tmp_ns1__runDnaparsResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnaparsResponse(soap, &soap_tmp_ns1__runDnaparsResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnaparsResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnapars(soap, &soap_tmp_ns1__runDnapars);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnapars(soap, &soap_tmp_ns1__runDnapars, "ns1:runDnapars", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnapars(soap, soap_tmp_ns1__runDnapars._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnaparsResponse(soap, &soap_tmp_ns1__runDnaparsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnaparsResponse(soap, &soap_tmp_ns1__runDnaparsResponse, "ns1:runDnaparsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnaparsResponse(soap, &soap_tmp_ns1__runDnaparsResponse, "ns1:runDnaparsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnapenny(struct soap *soap)
{	struct ns1__runDnapenny soap_tmp_ns1__runDnapenny;
	struct ns1__runDnapennyResponse soap_tmp_ns1__runDnapennyResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnapennyResponse(soap, &soap_tmp_ns1__runDnapennyResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnapennyResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnapenny(soap, &soap_tmp_ns1__runDnapenny);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnapenny(soap, &soap_tmp_ns1__runDnapenny, "ns1:runDnapenny", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnapenny(soap, soap_tmp_ns1__runDnapenny._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnapennyResponse(soap, &soap_tmp_ns1__runDnapennyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnapennyResponse(soap, &soap_tmp_ns1__runDnapennyResponse, "ns1:runDnapennyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnapennyResponse(soap, &soap_tmp_ns1__runDnapennyResponse, "ns1:runDnapennyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnacomp(struct soap *soap)
{	struct ns1__runDnacomp soap_tmp_ns1__runDnacomp;
	struct ns1__runDnacompResponse soap_tmp_ns1__runDnacompResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnacompResponse(soap, &soap_tmp_ns1__runDnacompResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnacompResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnacomp(soap, &soap_tmp_ns1__runDnacomp);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnacomp(soap, &soap_tmp_ns1__runDnacomp, "ns1:runDnacomp", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnacomp(soap, soap_tmp_ns1__runDnacomp._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnacompResponse(soap, &soap_tmp_ns1__runDnacompResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnacompResponse(soap, &soap_tmp_ns1__runDnacompResponse, "ns1:runDnacompResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnacompResponse(soap, &soap_tmp_ns1__runDnacompResponse, "ns1:runDnacompResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnainvar(struct soap *soap)
{	struct ns1__runDnainvar soap_tmp_ns1__runDnainvar;
	struct ns1__runDnainvarResponse soap_tmp_ns1__runDnainvarResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnainvarResponse(soap, &soap_tmp_ns1__runDnainvarResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnainvarResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnainvar(soap, &soap_tmp_ns1__runDnainvar);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnainvar(soap, &soap_tmp_ns1__runDnainvar, "ns1:runDnainvar", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnainvar(soap, soap_tmp_ns1__runDnainvar._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnainvarResponse(soap, &soap_tmp_ns1__runDnainvarResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnainvarResponse(soap, &soap_tmp_ns1__runDnainvarResponse, "ns1:runDnainvarResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnainvarResponse(soap, &soap_tmp_ns1__runDnainvarResponse, "ns1:runDnainvarResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnaml(struct soap *soap)
{	struct ns1__runDnaml soap_tmp_ns1__runDnaml;
	struct ns1__runDnamlResponse soap_tmp_ns1__runDnamlResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnamlResponse(soap, &soap_tmp_ns1__runDnamlResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnamlResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnaml(soap, &soap_tmp_ns1__runDnaml);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnaml(soap, &soap_tmp_ns1__runDnaml, "ns1:runDnaml", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnaml(soap, soap_tmp_ns1__runDnaml._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnamlResponse(soap, &soap_tmp_ns1__runDnamlResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnamlResponse(soap, &soap_tmp_ns1__runDnamlResponse, "ns1:runDnamlResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnamlResponse(soap, &soap_tmp_ns1__runDnamlResponse, "ns1:runDnamlResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnamlk(struct soap *soap)
{	struct ns1__runDnamlk soap_tmp_ns1__runDnamlk;
	struct ns1__runDnamlkResponse soap_tmp_ns1__runDnamlkResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnamlkResponse(soap, &soap_tmp_ns1__runDnamlkResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnamlkResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnamlk(soap, &soap_tmp_ns1__runDnamlk);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnamlk(soap, &soap_tmp_ns1__runDnamlk, "ns1:runDnamlk", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnamlk(soap, soap_tmp_ns1__runDnamlk._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnamlkResponse(soap, &soap_tmp_ns1__runDnamlkResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnamlkResponse(soap, &soap_tmp_ns1__runDnamlkResponse, "ns1:runDnamlkResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnamlkResponse(soap, &soap_tmp_ns1__runDnamlkResponse, "ns1:runDnamlkResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDnadist(struct soap *soap)
{	struct ns1__runDnadist soap_tmp_ns1__runDnadist;
	struct ns1__runDnadistResponse soap_tmp_ns1__runDnadistResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDnadistResponse(soap, &soap_tmp_ns1__runDnadistResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDnadistResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDnadist(soap, &soap_tmp_ns1__runDnadist);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDnadist(soap, &soap_tmp_ns1__runDnadist, "ns1:runDnadist", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDnadist(soap, soap_tmp_ns1__runDnadist._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDnadistResponse(soap, &soap_tmp_ns1__runDnadistResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDnadistResponse(soap, &soap_tmp_ns1__runDnadistResponse, "ns1:runDnadistResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDnadistResponse(soap, &soap_tmp_ns1__runDnadistResponse, "ns1:runDnadistResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runGendist(struct soap *soap)
{	struct ns1__runGendist soap_tmp_ns1__runGendist;
	struct ns1__runGendistResponse soap_tmp_ns1__runGendistResponse;
	char * soap_tmp_string;
	soap_default_ns1__runGendistResponse(soap, &soap_tmp_ns1__runGendistResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runGendistResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runGendist(soap, &soap_tmp_ns1__runGendist);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runGendist(soap, &soap_tmp_ns1__runGendist, "ns1:runGendist", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runGendist(soap, soap_tmp_ns1__runGendist._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runGendistResponse(soap, &soap_tmp_ns1__runGendistResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runGendistResponse(soap, &soap_tmp_ns1__runGendistResponse, "ns1:runGendistResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runGendistResponse(soap, &soap_tmp_ns1__runGendistResponse, "ns1:runGendistResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runSeqboot(struct soap *soap)
{	struct ns1__runSeqboot soap_tmp_ns1__runSeqboot;
	struct ns1__runSeqbootResponse soap_tmp_ns1__runSeqbootResponse;
	char * soap_tmp_string;
	soap_default_ns1__runSeqbootResponse(soap, &soap_tmp_ns1__runSeqbootResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runSeqbootResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runSeqboot(soap, &soap_tmp_ns1__runSeqboot);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runSeqboot(soap, &soap_tmp_ns1__runSeqboot, "ns1:runSeqboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runSeqboot(soap, soap_tmp_ns1__runSeqboot._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runSeqbootResponse(soap, &soap_tmp_ns1__runSeqbootResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runSeqbootResponse(soap, &soap_tmp_ns1__runSeqbootResponse, "ns1:runSeqbootResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runSeqbootResponse(soap, &soap_tmp_ns1__runSeqbootResponse, "ns1:runSeqbootResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runRestml(struct soap *soap)
{	struct ns1__runRestml soap_tmp_ns1__runRestml;
	struct ns1__runRestmlResponse soap_tmp_ns1__runRestmlResponse;
	char * soap_tmp_string;
	soap_default_ns1__runRestmlResponse(soap, &soap_tmp_ns1__runRestmlResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runRestmlResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runRestml(soap, &soap_tmp_ns1__runRestml);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runRestml(soap, &soap_tmp_ns1__runRestml, "ns1:runRestml", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runRestml(soap, soap_tmp_ns1__runRestml._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runRestmlResponse(soap, &soap_tmp_ns1__runRestmlResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runRestmlResponse(soap, &soap_tmp_ns1__runRestmlResponse, "ns1:runRestmlResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runRestmlResponse(soap, &soap_tmp_ns1__runRestmlResponse, "ns1:runRestmlResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runClique(struct soap *soap)
{	struct ns1__runClique soap_tmp_ns1__runClique;
	struct ns1__runCliqueResponse soap_tmp_ns1__runCliqueResponse;
	char * soap_tmp_string;
	soap_default_ns1__runCliqueResponse(soap, &soap_tmp_ns1__runCliqueResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runCliqueResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runClique(soap, &soap_tmp_ns1__runClique);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runClique(soap, &soap_tmp_ns1__runClique, "ns1:runClique", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runClique(soap, soap_tmp_ns1__runClique._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runCliqueResponse(soap, &soap_tmp_ns1__runCliqueResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runCliqueResponse(soap, &soap_tmp_ns1__runCliqueResponse, "ns1:runCliqueResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runCliqueResponse(soap, &soap_tmp_ns1__runCliqueResponse, "ns1:runCliqueResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runFitch(struct soap *soap)
{	struct ns1__runFitch soap_tmp_ns1__runFitch;
	struct ns1__runFitchResponse soap_tmp_ns1__runFitchResponse;
	char * soap_tmp_string;
	soap_default_ns1__runFitchResponse(soap, &soap_tmp_ns1__runFitchResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runFitchResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runFitch(soap, &soap_tmp_ns1__runFitch);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runFitch(soap, &soap_tmp_ns1__runFitch, "ns1:runFitch", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runFitch(soap, soap_tmp_ns1__runFitch._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runFitchResponse(soap, &soap_tmp_ns1__runFitchResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runFitchResponse(soap, &soap_tmp_ns1__runFitchResponse, "ns1:runFitchResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runFitchResponse(soap, &soap_tmp_ns1__runFitchResponse, "ns1:runFitchResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runKitsch(struct soap *soap)
{	struct ns1__runKitsch soap_tmp_ns1__runKitsch;
	struct ns1__runKitschResponse soap_tmp_ns1__runKitschResponse;
	char * soap_tmp_string;
	soap_default_ns1__runKitschResponse(soap, &soap_tmp_ns1__runKitschResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runKitschResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runKitsch(soap, &soap_tmp_ns1__runKitsch);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runKitsch(soap, &soap_tmp_ns1__runKitsch, "ns1:runKitsch", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runKitsch(soap, soap_tmp_ns1__runKitsch._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runKitschResponse(soap, &soap_tmp_ns1__runKitschResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runKitschResponse(soap, &soap_tmp_ns1__runKitschResponse, "ns1:runKitschResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runKitschResponse(soap, &soap_tmp_ns1__runKitschResponse, "ns1:runKitschResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runNeighbor(struct soap *soap)
{	struct ns1__runNeighbor soap_tmp_ns1__runNeighbor;
	struct ns1__runNeighborResponse soap_tmp_ns1__runNeighborResponse;
	char * soap_tmp_string;
	soap_default_ns1__runNeighborResponse(soap, &soap_tmp_ns1__runNeighborResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runNeighborResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runNeighbor(soap, &soap_tmp_ns1__runNeighbor);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runNeighbor(soap, &soap_tmp_ns1__runNeighbor, "ns1:runNeighbor", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runNeighbor(soap, soap_tmp_ns1__runNeighbor._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runNeighborResponse(soap, &soap_tmp_ns1__runNeighborResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runNeighborResponse(soap, &soap_tmp_ns1__runNeighborResponse, "ns1:runNeighborResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runNeighborResponse(soap, &soap_tmp_ns1__runNeighborResponse, "ns1:runNeighborResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runContml(struct soap *soap)
{	struct ns1__runContml soap_tmp_ns1__runContml;
	struct ns1__runContmlResponse soap_tmp_ns1__runContmlResponse;
	char * soap_tmp_string;
	soap_default_ns1__runContmlResponse(soap, &soap_tmp_ns1__runContmlResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runContmlResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runContml(soap, &soap_tmp_ns1__runContml);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runContml(soap, &soap_tmp_ns1__runContml, "ns1:runContml", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runContml(soap, soap_tmp_ns1__runContml._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runContmlResponse(soap, &soap_tmp_ns1__runContmlResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runContmlResponse(soap, &soap_tmp_ns1__runContmlResponse, "ns1:runContmlResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runContmlResponse(soap, &soap_tmp_ns1__runContmlResponse, "ns1:runContmlResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runMix(struct soap *soap)
{	struct ns1__runMix soap_tmp_ns1__runMix;
	struct ns1__runMixResponse soap_tmp_ns1__runMixResponse;
	char * soap_tmp_string;
	soap_default_ns1__runMixResponse(soap, &soap_tmp_ns1__runMixResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runMixResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runMix(soap, &soap_tmp_ns1__runMix);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runMix(soap, &soap_tmp_ns1__runMix, "ns1:runMix", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runMix(soap, soap_tmp_ns1__runMix._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runMixResponse(soap, &soap_tmp_ns1__runMixResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runMixResponse(soap, &soap_tmp_ns1__runMixResponse, "ns1:runMixResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runMixResponse(soap, &soap_tmp_ns1__runMixResponse, "ns1:runMixResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runPenny(struct soap *soap)
{	struct ns1__runPenny soap_tmp_ns1__runPenny;
	struct ns1__runPennyResponse soap_tmp_ns1__runPennyResponse;
	char * soap_tmp_string;
	soap_default_ns1__runPennyResponse(soap, &soap_tmp_ns1__runPennyResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runPennyResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runPenny(soap, &soap_tmp_ns1__runPenny);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runPenny(soap, &soap_tmp_ns1__runPenny, "ns1:runPenny", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runPenny(soap, soap_tmp_ns1__runPenny._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runPennyResponse(soap, &soap_tmp_ns1__runPennyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runPennyResponse(soap, &soap_tmp_ns1__runPennyResponse, "ns1:runPennyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runPennyResponse(soap, &soap_tmp_ns1__runPennyResponse, "ns1:runPennyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDollop(struct soap *soap)
{	struct ns1__runDollop soap_tmp_ns1__runDollop;
	struct ns1__runDollopResponse soap_tmp_ns1__runDollopResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDollopResponse(soap, &soap_tmp_ns1__runDollopResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDollopResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDollop(soap, &soap_tmp_ns1__runDollop);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDollop(soap, &soap_tmp_ns1__runDollop, "ns1:runDollop", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDollop(soap, soap_tmp_ns1__runDollop._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDollopResponse(soap, &soap_tmp_ns1__runDollopResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDollopResponse(soap, &soap_tmp_ns1__runDollopResponse, "ns1:runDollopResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDollopResponse(soap, &soap_tmp_ns1__runDollopResponse, "ns1:runDollopResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runDolpenny(struct soap *soap)
{	struct ns1__runDolpenny soap_tmp_ns1__runDolpenny;
	struct ns1__runDolpennyResponse soap_tmp_ns1__runDolpennyResponse;
	char * soap_tmp_string;
	soap_default_ns1__runDolpennyResponse(soap, &soap_tmp_ns1__runDolpennyResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runDolpennyResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runDolpenny(soap, &soap_tmp_ns1__runDolpenny);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runDolpenny(soap, &soap_tmp_ns1__runDolpenny, "ns1:runDolpenny", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runDolpenny(soap, soap_tmp_ns1__runDolpenny._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runDolpennyResponse(soap, &soap_tmp_ns1__runDolpennyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runDolpennyResponse(soap, &soap_tmp_ns1__runDolpennyResponse, "ns1:runDolpennyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runDolpennyResponse(soap, &soap_tmp_ns1__runDolpennyResponse, "ns1:runDolpennyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runPsort(struct soap *soap)
{	struct ns1__runPsort soap_tmp_ns1__runPsort;
	struct ns1__runPsortResponse soap_tmp_ns1__runPsortResponse;
	char * soap_tmp_string;
	soap_default_ns1__runPsortResponse(soap, &soap_tmp_ns1__runPsortResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runPsortResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runPsort(soap, &soap_tmp_ns1__runPsort);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runPsort(soap, &soap_tmp_ns1__runPsort, "ns1:runPsort", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runPsort(soap, soap_tmp_ns1__runPsort._in0, soap_tmp_ns1__runPsort._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runPsortResponse(soap, &soap_tmp_ns1__runPsortResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runPsortResponse(soap, &soap_tmp_ns1__runPsortResponse, "ns1:runPsortResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runPsortResponse(soap, &soap_tmp_ns1__runPsortResponse, "ns1:runPsortResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runPsort2(struct soap *soap)
{	struct ns1__runPsort2 soap_tmp_ns1__runPsort2;
	struct ns1__runPsort2Response soap_tmp_ns1__runPsort2Response;
	char * soap_tmp_string;
	soap_default_ns1__runPsort2Response(soap, &soap_tmp_ns1__runPsort2Response);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runPsort2Response._jobid = &soap_tmp_string;
	soap_default_ns1__runPsort2(soap, &soap_tmp_ns1__runPsort2);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runPsort2(soap, &soap_tmp_ns1__runPsort2, "ns1:runPsort2", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runPsort2(soap, soap_tmp_ns1__runPsort2._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runPsort2Response(soap, &soap_tmp_ns1__runPsort2Response);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runPsort2Response(soap, &soap_tmp_ns1__runPsort2Response, "ns1:runPsort2Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runPsort2Response(soap, &soap_tmp_ns1__runPsort2Response, "ns1:runPsort2Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runPsortb(struct soap *soap)
{	struct ns1__runPsortb soap_tmp_ns1__runPsortb;
	struct ns1__runPsortbResponse soap_tmp_ns1__runPsortbResponse;
	char * soap_tmp_string;
	soap_default_ns1__runPsortbResponse(soap, &soap_tmp_ns1__runPsortbResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runPsortbResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runPsortb(soap, &soap_tmp_ns1__runPsortb);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runPsortb(soap, &soap_tmp_ns1__runPsortb, "ns1:runPsortb", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runPsortb(soap, soap_tmp_ns1__runPsortb._in0, soap_tmp_ns1__runPsortb._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runPsortbResponse(soap, &soap_tmp_ns1__runPsortbResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runPsortbResponse(soap, &soap_tmp_ns1__runPsortbResponse, "ns1:runPsortbResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runPsortbResponse(soap, &soap_tmp_ns1__runPsortbResponse, "ns1:runPsortbResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runSsearch(struct soap *soap)
{	struct ns1__runSsearch soap_tmp_ns1__runSsearch;
	struct ns1__runSsearchResponse soap_tmp_ns1__runSsearchResponse;
	char * soap_tmp_string;
	soap_default_ns1__runSsearchResponse(soap, &soap_tmp_ns1__runSsearchResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runSsearchResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runSsearch(soap, &soap_tmp_ns1__runSsearch);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runSsearch(soap, &soap_tmp_ns1__runSsearch, "ns1:runSsearch", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runSsearch(soap, soap_tmp_ns1__runSsearch._in0, soap_tmp_ns1__runSsearch._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runSsearchResponse(soap, &soap_tmp_ns1__runSsearchResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runSsearchResponse(soap, &soap_tmp_ns1__runSsearchResponse, "ns1:runSsearchResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runSsearchResponse(soap, &soap_tmp_ns1__runSsearchResponse, "ns1:runSsearchResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runTcoffee(struct soap *soap)
{	struct ns1__runTcoffee soap_tmp_ns1__runTcoffee;
	struct ns1__runTcoffeeResponse soap_tmp_ns1__runTcoffeeResponse;
	char * soap_tmp_string;
	soap_default_ns1__runTcoffeeResponse(soap, &soap_tmp_ns1__runTcoffeeResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runTcoffeeResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runTcoffee(soap, &soap_tmp_ns1__runTcoffee);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runTcoffee(soap, &soap_tmp_ns1__runTcoffee, "ns1:runTcoffee", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runTcoffee(soap, soap_tmp_ns1__runTcoffee._in0, soap_tmp_ns1__runTcoffee._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runTcoffeeResponse(soap, &soap_tmp_ns1__runTcoffeeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runTcoffeeResponse(soap, &soap_tmp_ns1__runTcoffeeResponse, "ns1:runTcoffeeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runTcoffeeResponse(soap, &soap_tmp_ns1__runTcoffeeResponse, "ns1:runTcoffeeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runtRNAscan(struct soap *soap)
{	struct ns1__runtRNAscan soap_tmp_ns1__runtRNAscan;
	struct ns1__runtRNAscanResponse soap_tmp_ns1__runtRNAscanResponse;
	char * soap_tmp_string;
	soap_default_ns1__runtRNAscanResponse(soap, &soap_tmp_ns1__runtRNAscanResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runtRNAscanResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runtRNAscan(soap, &soap_tmp_ns1__runtRNAscan);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runtRNAscan(soap, &soap_tmp_ns1__runtRNAscan, "ns1:runtRNAscan", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runtRNAscan(soap, soap_tmp_ns1__runtRNAscan._in0, soap_tmp_ns1__runtRNAscan._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runtRNAscanResponse(soap, &soap_tmp_ns1__runtRNAscanResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runtRNAscanResponse(soap, &soap_tmp_ns1__runtRNAscanResponse, "ns1:runtRNAscanResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runtRNAscanResponse(soap, &soap_tmp_ns1__runtRNAscanResponse, "ns1:runtRNAscanResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runWeblogo(struct soap *soap)
{	struct ns1__runWeblogo soap_tmp_ns1__runWeblogo;
	struct ns1__runWeblogoResponse soap_tmp_ns1__runWeblogoResponse;
	char * soap_tmp_string;
	soap_default_ns1__runWeblogoResponse(soap, &soap_tmp_ns1__runWeblogoResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runWeblogoResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runWeblogo(soap, &soap_tmp_ns1__runWeblogo);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runWeblogo(soap, &soap_tmp_ns1__runWeblogo, "ns1:runWeblogo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runWeblogo(soap, soap_tmp_ns1__runWeblogo._in0, soap_tmp_ns1__runWeblogo._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runWeblogoResponse(soap, &soap_tmp_ns1__runWeblogoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runWeblogoResponse(soap, &soap_tmp_ns1__runWeblogoResponse, "ns1:runWeblogoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runWeblogoResponse(soap, &soap_tmp_ns1__runWeblogoResponse, "ns1:runWeblogoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runWolfPsort(struct soap *soap)
{	struct ns1__runWolfPsort soap_tmp_ns1__runWolfPsort;
	struct ns1__runWolfPsortResponse soap_tmp_ns1__runWolfPsortResponse;
	char * soap_tmp_string;
	soap_default_ns1__runWolfPsortResponse(soap, &soap_tmp_ns1__runWolfPsortResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runWolfPsortResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runWolfPsort(soap, &soap_tmp_ns1__runWolfPsort);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runWolfPsort(soap, &soap_tmp_ns1__runWolfPsort, "ns1:runWolfPsort", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runWolfPsort(soap, soap_tmp_ns1__runWolfPsort._in0, soap_tmp_ns1__runWolfPsort._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runWolfPsortResponse(soap, &soap_tmp_ns1__runWolfPsortResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runWolfPsortResponse(soap, &soap_tmp_ns1__runWolfPsortResponse, "ns1:runWolfPsortResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runWolfPsortResponse(soap, &soap_tmp_ns1__runWolfPsortResponse, "ns1:runWolfPsortResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__runRNAfold(struct soap *soap)
{	struct ns1__runRNAfold soap_tmp_ns1__runRNAfold;
	struct ns1__runRNAfoldResponse soap_tmp_ns1__runRNAfoldResponse;
	char * soap_tmp_string;
	soap_default_ns1__runRNAfoldResponse(soap, &soap_tmp_ns1__runRNAfoldResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__runRNAfoldResponse._jobid = &soap_tmp_string;
	soap_default_ns1__runRNAfold(soap, &soap_tmp_ns1__runRNAfold);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__runRNAfold(soap, &soap_tmp_ns1__runRNAfold, "ns1:runRNAfold", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__runRNAfold(soap, soap_tmp_ns1__runRNAfold._in0, soap_tmp_ns1__runRNAfold._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__runRNAfoldResponse(soap, &soap_tmp_ns1__runRNAfoldResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__runRNAfoldResponse(soap, &soap_tmp_ns1__runRNAfoldResponse, "ns1:runRNAfoldResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__runRNAfoldResponse(soap, &soap_tmp_ns1__runRNAfoldResponse, "ns1:runRNAfoldResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__showBlastDB(struct soap *soap)
{	struct ns1__showBlastDB soap_tmp_ns1__showBlastDB;
	struct ns1__showBlastDBResponse soap_tmp_ns1__showBlastDBResponse;
	char * soap_tmp_string;
	soap_default_ns1__showBlastDBResponse(soap, &soap_tmp_ns1__showBlastDBResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__showBlastDBResponse._dblist = &soap_tmp_string;
	soap_default_ns1__showBlastDB(soap, &soap_tmp_ns1__showBlastDB);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__showBlastDB(soap, &soap_tmp_ns1__showBlastDB, "ns1:showBlastDB", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__showBlastDB(soap, soap_tmp_ns1__showBlastDB._params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__showBlastDBResponse(soap, &soap_tmp_ns1__showBlastDBResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__showBlastDBResponse(soap, &soap_tmp_ns1__showBlastDBResponse, "ns1:showBlastDBResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__showBlastDBResponse(soap, &soap_tmp_ns1__showBlastDBResponse, "ns1:showBlastDBResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__map2PathwayProjector(struct soap *soap)
{	struct ns1__map2PathwayProjector soap_tmp_ns1__map2PathwayProjector;
	struct ns1__map2PathwayProjectorResponse soap_tmp_ns1__map2PathwayProjectorResponse;
	char * soap_tmp_string;
	soap_default_ns1__map2PathwayProjectorResponse(soap, &soap_tmp_ns1__map2PathwayProjectorResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__map2PathwayProjectorResponse._jobid = &soap_tmp_string;
	soap_default_ns1__map2PathwayProjector(soap, &soap_tmp_ns1__map2PathwayProjector);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__map2PathwayProjector(soap, &soap_tmp_ns1__map2PathwayProjector, "ns1:map2PathwayProjector", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__map2PathwayProjector(soap, soap_tmp_ns1__map2PathwayProjector._in0, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__map2PathwayProjectorResponse(soap, &soap_tmp_ns1__map2PathwayProjectorResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__map2PathwayProjectorResponse(soap, &soap_tmp_ns1__map2PathwayProjectorResponse, "ns1:map2PathwayProjectorResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__map2PathwayProjectorResponse(soap, &soap_tmp_ns1__map2PathwayProjectorResponse, "ns1:map2PathwayProjectorResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__checkStatus(struct soap *soap)
{	struct ns1__checkStatus soap_tmp_ns1__checkStatus;
	struct ns1__checkStatusResponse soap_tmp_ns1__checkStatusResponse;
	int soap_tmp_int;
	soap_default_ns1__checkStatusResponse(soap, &soap_tmp_ns1__checkStatusResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__checkStatusResponse._status = &soap_tmp_int;
	soap_default_ns1__checkStatus(soap, &soap_tmp_ns1__checkStatus);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__checkStatus(soap, &soap_tmp_ns1__checkStatus, "ns1:checkStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__checkStatus(soap, soap_tmp_ns1__checkStatus._jobid, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__checkStatusResponse(soap, &soap_tmp_ns1__checkStatusResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__checkStatusResponse(soap, &soap_tmp_ns1__checkStatusResponse, "ns1:checkStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__checkStatusResponse(soap, &soap_tmp_ns1__checkStatusResponse, "ns1:checkStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__checkStatus_USCOREretJobid(struct soap *soap)
{	struct ns1__checkStatus_USCOREretJobid soap_tmp_ns1__checkStatus_USCOREretJobid;
	struct ns1__checkStatus_USCOREretJobidResponse soap_tmp_ns1__checkStatus_USCOREretJobidResponse;
	char * soap_tmp_string;
	soap_default_ns1__checkStatus_USCOREretJobidResponse(soap, &soap_tmp_ns1__checkStatus_USCOREretJobidResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__checkStatus_USCOREretJobidResponse._jobid_USCOREout = &soap_tmp_string;
	soap_default_ns1__checkStatus_USCOREretJobid(soap, &soap_tmp_ns1__checkStatus_USCOREretJobid);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__checkStatus_USCOREretJobid(soap, &soap_tmp_ns1__checkStatus_USCOREretJobid, "ns1:checkStatus_retJobid", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__checkStatus_USCOREretJobid(soap, soap_tmp_ns1__checkStatus_USCOREretJobid._jobid_USCOREin, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__checkStatus_USCOREretJobidResponse(soap, &soap_tmp_ns1__checkStatus_USCOREretJobidResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__checkStatus_USCOREretJobidResponse(soap, &soap_tmp_ns1__checkStatus_USCOREretJobidResponse, "ns1:checkStatus_retJobidResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__checkStatus_USCOREretJobidResponse(soap, &soap_tmp_ns1__checkStatus_USCOREretJobidResponse, "ns1:checkStatus_retJobidResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__getResult(struct soap *soap)
{	struct ns1__getResult soap_tmp_ns1__getResult;
	struct ns1__getResultResponse soap_tmp_ns1__getResultResponse;
	char * soap_tmp_string;
	soap_default_ns1__getResultResponse(soap, &soap_tmp_ns1__getResultResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__getResultResponse._result = &soap_tmp_string;
	soap_default_ns1__getResult(soap, &soap_tmp_ns1__getResult);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__getResult(soap, &soap_tmp_ns1__getResult, "ns1:getResult", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__getResult(soap, soap_tmp_ns1__getResult._jobid, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__getResultResponse(soap, &soap_tmp_ns1__getResultResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getResultResponse(soap, &soap_tmp_ns1__getResultResponse, "ns1:getResultResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getResultResponse(soap, &soap_tmp_ns1__getResultResponse, "ns1:getResultResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__getMultiResult(struct soap *soap)
{	struct ns1__getMultiResult soap_tmp_ns1__getMultiResult;
	struct ns1__getMultiResultResponse soap_tmp_ns1__getMultiResultResponse;
	char * soap_tmp_string;
	soap_default_ns1__getMultiResultResponse(soap, &soap_tmp_ns1__getMultiResultResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__getMultiResultResponse._result = &soap_tmp_string;
	soap_default_ns1__getMultiResult(soap, &soap_tmp_ns1__getMultiResult);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__getMultiResult(soap, &soap_tmp_ns1__getMultiResult, "ns1:getMultiResult", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__getMultiResult(soap, soap_tmp_ns1__getMultiResult._jobid, soap_tmp_ns1__getMultiResult._type, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__getMultiResultResponse(soap, &soap_tmp_ns1__getMultiResultResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getMultiResultResponse(soap, &soap_tmp_ns1__getMultiResultResponse, "ns1:getMultiResultResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getMultiResultResponse(soap, &soap_tmp_ns1__getMultiResultResponse, "ns1:getMultiResultResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
